### ISSUE TITLE
Add telex typing style for Vietnamese language

### ISSUE THREAD

**Issue by LAM-GIA-THINH** [futo-org/android-keyboard#396] opened 2024-07-30 03:00 UTC
### Use Cases

Most if not all Vietnamese use the Telex typing style. The current typing style on the app is rarely use by anyone that speak the language.

**Comment by kfidaw4ir** [comment] 2024-08-04 18:00
Duplication of #50

**Comment by abb128** [comment] 2024-08-05 10:36
Closing as duplicate of #50

**Closed by abb128** 2024-08-05 10:36 UTC
Labels: enhancement, new
