### ISSUE TITLE
Disable Auto Capitalization in Voice Input

### ISSUE THREAD

**Issue by ykuksenko** [futo-org/android-keyboard#150] opened 2024-07-03 16:11 UTC
It seems any time I do voice input the first letter is capitalized. Sometimes I need to enter a single word and do not want it capitalized, for example if I am in the middle a sentence trying to edit.
A toggle in the voice input section to turn off auto capitalization or force it off would be great.

Thank you for creating this software!

**Comment by dean-futo** [comment] 2024-10-20 03:55
Consolidated into #663

**Comment by dean-futo** [comment] 2024-10-23 23:19
Duplicate of #520 - see that issue for details.

**Closed by dean-futo** 2024-10-23 23:19 UTC
Labels: Feature Request, Low Priority, Low Complexity, Consolidated
