### ISSUE TITLE
[Feature Request] disable end of word cursor snapping

### ISSUE THREAD

**Issue by FireNinja7365** [futo-org/android-keyboard#350] opened 2024-07-24 05:20 UTC
Make an option to turn off the feature where the cursor snaps to the end of words when moved

**Comment by Tema726** [comment] 2024-08-01 10:50
Yes please!

**Comment by DavidBevi** [comment] 2024-08-05 07:43
Oh!, that's what was wrong yesterday when I was in a hurry.
Yes please, if I tap mid-word it's because I want the cursor mid-word!!!

**Comment by Timothy-Ecc19** [comment] 2024-08-15 01:55
The ability to disable cursor auto snaping to the end of words would be Wonderful!

**Comment by JellyJoe198** [comment] 2024-08-19 15:06
What is weird is it doesn't always move to the end, only after you've done certain actions which feel random if you're not used to them. See #267. The option to fully remove cursor snapping would solve both these issues.

**Comment by FireNinja7365** [comment] 2024-08-20 01:32
Idk what i did to mine but somehow i accidentally disabled it so I'm happy if they fix it or not lol

**Comment by abb128** [comment] 2024-09-27 22:09
Duplicate of #98

**Closed by abb128** 2024-09-27 22:09 UTC
