### ISSUE TITLE
Emoji Kitchen support

### ISSUE THREAD

**Issue by Mylloon** [futo-org/android-keyboard#575] opened 2024-09-30 12:16 UTC
### Use Cases

Open new emojis possibilities.

### Proposal

I'd like to see this feature on this app. Currently it's only available in the google one.

### References

- Playground: https://emojikitchen.dev/
- https://github.com/xsalazar/emoji-kitchen

**Comment by abb128** [comment] 2024-09-30 20:45
Duplicate of #214

**Closed by abb128** 2024-09-30 20:45 UTC
Labels: enhancement, new
