### ISSUE TITLE
[Feature Request] Option to disable symbols when long pressing a letter

### ISSUE THREAD

**Issue by edherjrrr** [futo-org/android-keyboard#72] opened 2024-06-29 21:40 UTC
When typing out a sentence in a language other than english, I find it very inconvenient to long press on a letter only to see a symbol instead of a character used to write actual words.

![Screenshot_20240629_183930_Brave](https://github.com/futo-org/android-keyboard/assets/105890328/e43d3d32-5177-4f8b-80cc-de55ac2052b6)

An example of what I mean is shown in the image.

**Comment by abb128** [comment] 2024-06-30 11:47
Seems to be duplicate of #18

**Closed by abb128** 2024-06-30 11:47 UTC
