### ISSUE TITLE
Auto Spacing Accidentally Removes Spaces

### ISSUE THREAD

**Issue by ShalokShalom** [futo-org/android-keyboard#815] opened 2024-11-13 09:47 UTC
### What happened?

Hi there :)

I HOPE this is unwanted behaviour.
At least, its undocumented and not described in the related setting:

Whenever I type ; after a word, it automatically REMOVES the space in front of it, that I just MANUALLY inputted before.

This is an issue for people, who like to end their sentences with an old fashioned emoji.

Disabling auto spacing (setting it to legacy) removes this undesired behaviour. 

### Keyboard Version

0.1.24-playstore

**Comment by abb128** [comment] 2024-11-18 15:57
This will be fixed in the next release

**Closed by abb128** 2024-11-18 15:57 UTC
Labels: Bug Report, Low Complexity, Very High Priority

**Comment by codethief** [comment] 2025-05-23 08:27
@abb128 What release was that or will that be? I'm on the current version 0.1.24.2-playstore right now and the issue is still occurring.

**Comment by ShalokShalom** [comment] 2025-05-23 13:28
I am also on  0.1.24.2-playstore and it doesn't effect me.

My settings:

![Image](https://github.com/user-attachments/assets/666641c5-c394-4090-b0f5-2369cb3ca77a)

![Image](https://github.com/user-attachments/assets/68a9beb1-9700-48d1-a3b9-22c87680f00b)
