### ISSUE TITLE
Fix Mid-Sentence Capitalization Issue When Resuming Dictation

### ISSUE THREAD

**Issue by SlappsMcChapply** [futo-org/android-keyboard#469] opened 2024-08-14 20:25 UTC
### What happened?

Galaxy 9. Android 10. Google Keep (in the video examples, but behavior consistent across all apps -- Firefox, Signal, et al).

What happens: You speak, pause to think mid-sentence, dictation auto-ends, you press to speak again, finish thought, first word's letter of that second (albeit mid-sentence) dictation result is capitalized when it shouldn't be.

Example: "What I find funny about it is [pause, transcription appears on-screen] That they don't even know what's happening." The word "That" should be "that" instead. FUTO will tend to add a period, which can be nice if it's really the end of a sentence, but the period frequently requires deleting to resume the unfinished thought or whatever, which then requires deleting the capital letter that begins the second transcription after it appears -- more "keyboard wrestling."

What should happen: The resumed dictation shouldn't have the first word's letter capitalized when mid-sentence.

Note: It doesn't happen 100%, but more often than not, and it 100% shouldn't happen, per grammar.

Videos:
https://github.com/user-attachments/assets/59ab8409-7496-4678-af04-d5ab7f2995b1
https://github.com/user-attachments/assets/44270c4c-e7ee-49ab-9c9b-7bcff397f61b

### Keyboard Version

0.1.23.2

**Comment by dean-futo** [comment] 2024-10-20 05:16
Consolidated into #663

**Comment by dean-futo** [comment] 2024-10-23 23:19
Duplicate of #520 - see that issue for details.

**Closed by dean-futo** 2024-10-23 23:19 UTC
Labels: Bug Report, Very High Priority, Medium Complexity
