### ISSUE TITLE
Add Option to Extend Voice Input Listening Duration

### ISSUE THREAD

**Issue by NotGovernor** [futo-org/android-keyboard#415] opened 2024-08-03 01:51 UTC
The stand alone futo voice app had a setting that allowed you to have it continue listening until you pressed the button. Please bring that back. The voice built into the new keyboard app stops listening at mid-sentence pauses.

Thanks! <3

**Comment by FaridZelli** [comment] 2024-10-16 16:27
I also find it quite hard to finish my sentences. Perhaps the default listing period should be increased as well, or made adjustable.

**Comment by dean-futo** [comment] 2024-11-03 03:17
Duplicate of #719 - merging this issue into that one.

**Closed by dean-futo** 2024-11-03 03:17 UTC
Labels: Feature Request, High Priority, Medium Complexity
