### ISSUE TITLE
Feature Request. Symbol preview on main keys

### ISSUE THREAD

**Issue by Kycirion** [futo-org/android-keyboard#138] opened 2024-07-03 02:33 UTC
It would be nice to have a small symbol preview on the top of each key to show the symbol you get on a long press.

**Comment by KuroiKoyani** [comment] 2024-07-03 12:50
@Kycirion  this feature is available in QWERTY keyboards: 

![Screenshot_20240703-144529](https://github.com/futo-org/android-keyboard/assets/75583934/37375baa-ab05-4e2c-a2e4-f4c0ea46615b)
![Screenshot_20240703-144905](https://github.com/futo-org/android-keyboard/assets/75583934/8d589145-0ea6-42b3-aa4c-95f3790b3c82)

**Comment by Kycirion** [comment] 2024-07-03 14:23
Ah, didn't see that in the options. Thanks!

**Comment by dancojocaru2000** [comment] 2024-07-04 04:18
@Kycirion If the issue is solved, consider closing it

**Comment by SuperDragonite2172** [comment] 2024-07-16 11:13
> @Kycirion this feature is available in QWERTY keyboards:
> 
> ![Screenshot_20240703-144529](https://private-user-images.githubusercontent.com/75583934/345426244-37375baa-ab05-4e2c-a2e4-f4c0ea46615b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjg1NTksIm5iZiI6MTcyMTEyODI1OSwicGF0aCI6Ii83NTU4MzkzNC8zNDU0MjYyNDQtMzczNzViYWEtYWIwNS00ZTJjLWEyZTQtZjRjMGVhNDY2MTViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDExMTA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhYjAzYzM3NmU3NzBjYzcxOWMxYjc5OWNhZWYwZmFkY2I3MjNjN2M4YTcxNTM0YWExYzU4MDBiODQ2NTY4MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QDci5hrggbvLc26b-JUy_czhjewOMm9Djkxqo6bRTSg) ![Screenshot_20240703-144905](https://private-user-images.githubusercontent.com/75583934/345427052-8d589145-0ea6-42b3-aa4c-95f3790b3c82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjg1NTksIm5iZiI6MTcyMTEyODI1OSwicGF0aCI6Ii83NTU4MzkzNC8zNDU0MjcwNTItOGQ1ODkxNDUtMGVhNi00MmIzLWFhNGMtOTVmMzc5MGIzYzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDExMTA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ODYxNDUxODhhNTIxMjJiODdjM2E3NmFkMzkzYTE4MThlMWZiYWEzYjIyMDhhMTQ3ZTJiM2M5MzkzOTMxY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4iLnVvF1PTUfzOjAxbfBBcJ3mGy8wXjBFf4Ob93K7UM)

I originally missed this option as well simply because I didn't scroll down.  To me the symbol hints make more sense under the Typing Preferences rather than Theme.  If it's to remain in Typing Preferences though, maybe move it to the top or have some way of indicating there's more options than just color schemes in the menu.

**Comment by abb128** [comment] 2024-07-16 15:02
Closing this as the option already exists. The option will be placed in a more sensical spot in the next version

**Closed by abb128** 2024-07-16 15:02 UTC
