### ISSUE TITLE
Possibility,  to pipe Audio Files like WhatsApp Voice Messages,  into the voice to text field. 

### ISSUE THREAD

**Issue by BenjaminSteimer** [futo-org/android-keyboard#785] opened 2024-11-11 14:28 UTC
### Use Cases

This would solve the issue of the times when people send voice messages, exactly when one cannot listen to them.

One shares the audio file to the Keyboard, and boom readable Text. 

### Proposal

-

**Comment by abb128** [comment] 2024-11-11 17:50
Duplicate of #657

**Closed by abb128** 2024-11-11 17:50 UTC
