### ISSUE TITLE
Option to disable contextual key

### ISSUE THREAD

**Issue by momsi** [futo-org/android-keyboard#978] opened 2024-12-24 13:20 UTC
### Use Cases

For example when typing in a browser address bar, a slash button appears right of the space bar. On narrower screens, this makes the spacebar relatively small. It often happens that I search/for/things/like/this. I'd suggest to be able to disable the contextual key to make the keyboard layout static. 

### Proposal

Add an option to disable the contextual key. Thus, maintaining a static key layout/position at all times.

**Comment by synapse-overload** [comment] 2024-12-25 15:11
This would be so great! The same key sometimes shows up in Whatsapp when chatting for some reason. It'd be great to remove any of the extra buttons on the spacebar row at will.

**Comment by dean-futo** [comment] 2024-12-28 00:02
Closing as duplicate of #953

**Closed by dean-futo** 2024-12-28 00:02 UTC
