### ISSUE TITLE
Feature Request: Multilingual Typing

### ISSUE THREAD

**Issue by Xpert-Guy** [futo-org/android-keyboard#140] opened 2024-07-03 06:30 UTC
Exactly what it says. I think it should be as simple as coding a toggle forma it to use other languages dictionaries.

**Comment by pirolisi** [comment] 2024-07-03 16:11
I'm trying the app and as far as I enjoy it ,I miss this feature to go back and forward in chat wiht  friends that speak different languages and not be forced to switch keyboard language.

**Comment by Xpert-Guy** [comment] 2024-07-04 00:56
Indeed. Multilingual typing is so important nowdays thanks to the many ways of finding people from varipus countries.

**Comment by codethief** [comment] 2024-07-04 08:14
I believe this is a duplicate of https://github.com/futo-org/android-keyboard/issues/38 ?

**Comment by Xpert-Guy** [comment] 2024-07-04 20:56
Oh I did not saw it, searched and looked throught some pages but I guess I did not saw that one.

**Comment by codethief** [comment] 2024-07-05 14:48
Let's close the present ticket then?

**Closed** 2024-07-08 06:38 UTC
