### ISSUE TITLE
remove emoji button when typing a url

### ISSUE THREAD

**Issue by FrankT423** [futo-org/android-keyboard#855] opened 2024-11-23 02:21 UTC
### Use Cases

With my current layout the bottom row from left to right is:symbols/numbers, comma, emoji, spacebar, period, and enter. When im on a URL text box,  between the spacebar and period there is a "/".This is a good convenience,  but makes the space bar quite small and easier to typo. 

### Proposal

I recommend removing the emoji button and replacing it with the / button (only for URLs, not in general). This would keep the spacebar size the same and would likely not effect most people negatively.

**Comment by dean-futo** [comment] 2024-11-24 00:16
Closing as a duplicate of #857

**Closed by dean-futo** 2024-11-24 00:16 UTC
