### ISSUE TITLE
make futo keyboard spell 2 languages ​​simultaneously

### ISSUE THREAD

**Issue by binocry** [futo-org/android-keyboard#990] opened 2024-12-29 02:04 UTC
### Use Cases

Like switfkey Keyboard from Microsoft, it's support spelling 2 language and it's easier for me instead have to menu or hold space to changes language manually

**Comment by dean-futo** [comment] 2024-12-29 06:09
Closing as duplicate of #683

**Closed by dean-futo** 2024-12-29 06:09 UTC
