### ISSUE TITLE
Add Option to Capitalize Words with Shift Key While Typing

### ISSUE THREAD

**Issue by Irique-pliskin** [futo-org/android-keyboard#474] opened 2024-08-15 16:01 UTC
### Use Cases

It's annoying that you have to select the word to capitalize it after it has been written

### Proposal

Samsung Keyboard let's you capitalize words just by placing the marker on the word and pressing the shift/caps key, and also capitalize words are added to suggestions while writing by pressing the shift/caps key

**Comment by The-Quantum-Alpha** [comment] 2024-08-16 22:44
You can long press the word and hit Shift. It will cycle through capitalizations.

**Comment by Irique-pliskin** [comment] 2024-08-17 11:34
> You can long press the word and hit Shift. It will cycle through capitalizations.

Thanks for the reply and sorry for not stating that I knew that.
What I want is the way Samsung Keyboard does it is to be implemented. Since I believe it would be better

**Comment by The-Quantum-Alpha** [comment] 2024-08-17 12:34
I understand. I am not affiliated to the project either. :)

Aug 17, 2024, 07:34 by ***@***.***:

**Comment by dean-futo** [comment] 2024-11-03 00:49
Duplicate of #23 - merging this request into that one.

**Closed by dean-futo** 2024-11-03 00:49 UTC
Labels: Feature Request, High Priority, Low Complexity
