### ISSUE TITLE
Horizontal keboard does not resize properly

### ISSUE THREAD

**Issue by mattvisa** [futo-org/android-keyboard#690] opened 2024-10-22 23:42 UTC
### What happened?

Horizontal keyboard cuts off the right side of the keyboard in pixel 8 pro running grapheneOS.

### Keyboard Version

Latest

### Text field info

Na

**Comment by mattvisa** [comment] 2024-10-22 23:50
Version 0.1.23.2

**Comment by jdenm8** [comment] 2024-10-27 14:44
Confirmed on a Pixel 6a. I think it's been since they pushed Android 15. 
![Screenshot_20241028-003613](https://github.com/user-attachments/assets/2c6f6d6b-8b30-468d-a955-194ae2407679)

I've also had Keyboard immediately and repeatedly self-close in landscape, have to turn the phone portrait to be able to type at all in certain contexts. Probably a separate bug.

Keyboard v0.1.23.2 F-Droid, Graphene 2024102400

**Comment by abb128** [comment] 2024-10-28 06:38
This should already be fixed in the latest pre-release or open testing on Google Play (v0.1.24-rc1), if it still continues on that version let me know.

**Closed by abb128** 2024-10-28 06:38 UTC
Labels: Bug Report, Medium Priority, Medium Complexity
