### ISSUE TITLE
Private Internal Dictionary Support

### ISSUE THREAD

**Issue by issuant** [futo-org/android-keyboard#650] opened 2024-10-17 01:05 UTC
### Use Cases

Same as #645. Finding out FUTOBoard used the system for its dictionary by default was an unpleasant surprise.

### Proposal

This is something not only Florisboard has but also Swiftkey though it is non-configurable there. 

In Florisboard, at the bottom of its 'Typing' settings page, there exists 'User dictionaries' which provides its own UI that allows activating or deactivating, configuring, and editing of both the internal and system dictionaries.

### References

- #645

**Comment by dean-futo** [comment] 2024-11-03 01:16
Duplicate of #645, as mentioned - merging this request into that one, which gives further detail.

**Closed by dean-futo** 2024-11-03 01:16 UTC
Labels: Feature Request, High Priority, Medium Complexity
