### ISSUE TITLE
Autocorrect and Prediction Stop Working Randomly

### ISSUE THREAD

**Issue by benjistokman** [futo-org/android-keyboard#502] opened 2024-08-24 04:55 UTC
### What happened?

I've tried everything from resetting the app about a dozen times and using older versions. But today, suddenly the prediction bar stops showing anything and autocorrect stops working randomly. It does not get fixed by force-quitting the app or restarting the phone. The only settings I've changed are disabling pop-up keys and personalized suggestions.

### Keyboard Version

0.1.22-3

**Comment by derekhansell** [comment] 2024-08-31 14:01
I have this problem. Autocorrect doesn't work when pressing the space bar in a LOT of apps and text boxes. So my messages are littered with errors. Even typing this up I typed "wwith" and the keyboard wanted to correct it to "with" but the spaelce bar didn't autocorrect.

**Comment by benjistokman** [comment] 2024-09-14 09:39
Okay so after a while I've observed it's just Voyager (Lemmy app) that does this? And it magically fixes itself if I open multitasking then go back into the app??

**Comment by dean-futo** [comment] 2024-10-20 05:55
Consolidated into #666

**Comment by dean-futo** [comment] 2024-10-23 18:39
Duplicate of #452 - see that issue for more details.

**Closed by dean-futo** 2024-10-23 18:39 UTC
Labels: Bug Report, Very High Priority, Medium Complexity
