### ISSUE TITLE
Forward Slash Showing Up on Keyboard in Browser Search When It Shouldn't

### ISSUE THREAD

**Issue by dean-futo** [futo-org/android-keyboard#857] opened 2024-11-24 00:12 UTC
### What happened?

The forward slash key, which has been removed from the main keyboard screen in the latest release, is showing up on the keyboard when searching in browsers. This is the case in Chrome, Firefox, Brave, DuckDuckGo, Edge, and presumably the rest.

### Keyboard Version

0.1.24

### Text field info

Email ticket #8593

**Comment by dean-futo** [comment] 2024-11-24 00:16
#855 is a duplicate - merged that issue into this one.

**Comment by abb128** [comment] 2024-11-27 16:28
Duplicate of #786

**Closed by abb128** 2024-11-27 16:28 UTC
Labels: Bug Report, Low Complexity, Very High Priority, Consolidated, Duplicate, Triaged, Email

**Comment by dean-futo** [comment] 2024-11-27 17:55
@abb128 merged
