### ISSUE TITLE
[Feature Request] Search bar in the emoji picker

### ISSUE THREAD

**Issue by nottisa** [futo-org/android-keyboard#71] opened 2024-06-29 21:38 UTC
This is fairly self explanatory, but I don't usually scroll through the emojis. I think having a search bar to go through them, similar to Gboard would be awesome.

**Comment by earth-walker** [comment] 2024-06-30 16:39
Additionally or alternatively, I would love to see the option to ONLY get predictive suggestions for emoji but not words.

**Comment by peter-vasut** [comment] 2024-07-02 22:49
In Signal, when you use their built-in emoji picker or text input, it searches in some localized database into your system language. Not sure if there is some database of emoji names for each language, or it just got translated with rest of the strings. This behavior is BAD. Use just the normal English variants which every app in existence (except Signal) uses, or search both, the localized and English versions, no matter what layout I'm using or what my system language is.

**Comment by nonetrix** [comment] 2024-07-04 09:01
Duplicate of https://github.com/futo-org/android-keyboard/issues/19

**Comment by abb128** [comment] 2024-07-13 11:08
Indeed this is a duplicate of #19, my bad

**Closed by abb128** 2024-07-13 11:08 UTC
Labels: enhancement, high-priority

**Comment by nottisa** [comment] 2024-07-13 12:31
Whoops, my bad, I'm always worried I won't find the other pr..
