### ISSUE TITLE
Allow disabling additional '/' key when using browser search or other URL entry

### ISSUE THREAD

**Issue by OpenSauce04** [futo-org/android-keyboard#895] opened 2024-11-28 12:07 UTC
### Use Cases

When typing in a browser search bar or other area where a URL may be entered, the space bar is made smaller to make space for an extra '/' key:
<img src=https://github.com/user-attachments/assets/1cc2ba3b-d798-4dff-92f5-039cfefd6493 width=300px/><img src=https://github.com/user-attachments/assets/2df733b6-4817-4d3e-acab-251ea759d7d6 width=300px/>
I find this change to be extremely intrusive to the extent that I have decided to not use the keyboard because the extra '/' key is positioned precisely where my thumb naturally reaches to hit the space bar, and whenever this extra key is active I type a handful of words "like/this/before/realizing" and have to go back and correct the mistake by awkwardly reaching my thumb an extra distance to the left to hit the space bar while typing.

### Proposal

This feature should be able to be disabled easily. I looked in the settings extensively and couldn't find any way for this to be turned off, so either a new option needs to be added to disable this or the existing method of disabling this that I missed needs to be made more discoverable.

**Comment by solgzr** [comment] 2024-11-28 18:01
I think this could be done the way it's in most android keyboards, where the "," key is replaced with "/" when cursor is in browser address bar, as "," is not something one usually types there.

![Screenshot_20241128-194421](https://github.com/user-attachments/assets/d36d7143-5443-45dd-83db-21cd0511ec9e)

**Comment by AndrewPaglusch** [comment] 2024-11-28 18:28
#786

**Comment by dean-futo** [comment] 2024-11-29 20:49
Closed as duplicate of #786

**Closed by dean-futo** 2024-11-29 20:49 UTC
