### ISSUE TITLE
Word editing jumps to last letter

### ISSUE THREAD

**Issue by te-simps** [futo-org/android-keyboard#369] opened 2024-07-26 14:03 UTC
When touching a word to edit by placing the cursor in the correct position, the cursor is next to the correct letter, but it jumps to the end of the word as soon as you hit the delete key. If I try and correct the spelling of ladfer to ladder, I get ladfe instead of lader once I press delete.

**Comment by Lu9-ST** [comment] 2024-08-20 17:07
hey, so yeah this is still happening pretty frequently and it's definitely getting pretty annoying and i hope something is done about it. It's kinda random too, like sometimes it just doesn't happen, but feels like it does more often than not.
another example: I'm trying to add a word/prefix ("hot") before another ("dog"), so i tap just before that word, but then it jumps to the end of the word and i end up typing "doghot" instead of "hotdog".

**Comment by tbAg69X** [comment] 2024-09-02 01:51
01SEP2024
I share these sentiments:

@te-simps "the cursor is next to the correct letter, but it jumps to the end of the word"
@namesarebloat "it still happens."
@Lu9-ST "still happening pretty frequently"
"pretty annoying"
"add a word/prefix... it jumps to the end of the word"

Cursor placement jumps to the end of the word. Highly counter productive to editing.

**Comment by AgentA1cr** [comment] 2024-09-11 11:24
This behavior might be considered a "feature", but if so, there should be an option to turn it off.

**Comment by abb128** [comment] 2024-09-27 22:10
Duplicate of #98

**Closed by abb128** 2024-09-27 22:10 UTC
