### ISSUE TITLE
Voice Recording Should Last Longer Without Auto Stop

### ISSUE THREAD

**Issue by peter-vasut** [futo-org/android-keyboard#133] opened 2024-07-02 22:39 UTC
Recording of the voice stops after a while without warning when you dictate longer text. You could possibly be in the middle of sentence. Ideally, the recognition would last until I press the screen (or I stop speaking, although the threshold for pause is bit short if you are thinking about what you want to say).

After recording stops, there is long processing phase blocking me from just enabling microphone again and continuing, which makes problem even worse.

If it's not possible to record for longer due to technical limitations, it should at least be indicated in UI by some visual element to see roughly how much time you have left. (If it's possible to transcribe audio in real-time, as described in #130, then there should be no limitation on how long can you speak.)

**Comment by FetchFast** [comment] 2024-07-12 13:43
Can you let the devs know how long it will go for 
and 
clarify that it does this even set to  manual rather than auto stop on silence

**Comment by dean-futo** [comment] 2024-11-03 04:31
Duplicate of #719 - merging this request into that one.

**Closed by dean-futo** 2024-11-03 04:31 UTC
Labels: Feature Request, High Priority, Medium Complexity
