### ISSUE TITLE
Spacebar reduction

### ISSUE THREAD

**Issue by PRIMAX7** [futo-org/android-keyboard#965] opened 2024-12-18 17:40 UTC
I've seen this bug when browsing in chrome. I don't know if this occurs somewhere else but the spacebar just reduces itself when browsing and adding a slash which wouldn't normally be there. I'll share the screenshot of both so you can see a better overview.

(The default one)
↓↓↓↓
 ![Screenshot_2024-12-18-22-48-45-014_org futo inputmethod latin playstore](https://github.com/user-attachments/assets/9ce3cf37-c37b-43cf-902d-7413233850c9)

(The bug interface)
↓↓↓↓
![Screenshot_2024-12-18-22-49-38-107_com android chrome](https://github.com/user-attachments/assets/f5d77323-e001-41b7-b179-db3596cf1df9)

I also had problem when coding using your keyboard. I personally use mimo when coding. When there are case to use only characters like (comma, underscores, periods and somerimes colons or quotes) it wont display in the screen.

Need a better emoji interface with more emoji. The 
current interface looks like from early 2000s. When text emoji pops up on bar it sometimes stays there until a next word is typed but othertimes it gets discarded from the tab after a single action. Most of the apps which I've used this feature where the emoji stays there in the tab until a new word is entered. So make that thing enabled so we can enter 2 or more of the same emojis at the same time. The ascii also needs more improvement.
Screenshot of current ASCII
↓↓↓↓
![Screenshot_2024-12-25-21-02-32-199_org futo inputmethod latin playstore](https://github.com/user-attachments/assets/cc3b3324-b99d-4bfe-83ee-01db6b9ff42c)

Hope you guys fix this ASAP.  Love your work and thanks for providing futo:) 

### Keyboard Version

v0.1.24-playstore

**Comment by arncor** [comment] 2024-12-19 21:48
I'm also annoyed by that slash which reduces the spacebar length

**Comment by rp25** [comment] 2024-12-21 02:03
I've noticed the same issue in firefox as well. 

Keyboard Version
v0.1.24

**Comment by rp25** [comment] 2024-12-21 02:06
The problem is fixed in firefox with rc1.

Try installing v0.1.24.1-rc1

**Comment by dean-futo** [comment] 2024-12-28 00:08
Closing as duplicate of #953

**Closed by dean-futo** 2024-12-28 00:08 UTC
Labels: Duplicate
