### ISSUE TITLE
Export keyboard settings

### ISSUE THREAD

**Issue by Tomassmits** [futo-org/android-keyboard#916] opened 2024-12-04 14:31 UTC
### Use Cases

As a user, I want to transfer my FUTO keyboard settings from one phone to the other, so I do not have to put in all the tweaks from my old phone. This will be useful if users replace their phone, or suggest certain settings to new users.

### Proposal

Add an export/import feature to quickly store and restore the keyboard settings.

**Comment by dean-futo** [comment] 2024-12-05 03:44
Closing as duplicate of #643

**Closed by dean-futo** 2024-12-05 03:44 UTC
