### ISSUE TITLE
Auto Capitalize Behavior Erratic After App Switching

### ISSUE THREAD

**Issue by AtmosphericHaze** [futo-org/android-keyboard#304] opened 2024-07-17 20:52 UTC
Option to start each sentence with upper case sometimes doesn't change to lower case and keeps writing in uppercase. It happens mainly after sending a message on one communicator and switching to another one. 
Phone is Xiaomi 12 Global. 
App Version 0.1.22-playstore
https://github.com/user-attachments/assets/cb92b3f7-7e9a-43a8-91f4-03dfe38c6fcf

**Comment by thesmart1** [comment] 2024-07-18 04:10
I experience the same issue. Caps lock remains on until all text is deleted and input is restarted.

**Comment by axel-kah** [comment] 2024-07-18 07:51
duplicate of #246

**Comment by dean-futo** [comment] 2024-10-20 05:16
Consolidated into #663

**Comment by dean-futo** [comment] 2024-10-20 05:17
Consolidated into #663

**Comment by dean-futo** [comment] 2024-10-24 00:46
Merged into #601 due to close similarity - see that issue for details.

**Closed by dean-futo** 2024-10-24 00:46 UTC
Labels: Bug Report, Very High Priority, Medium Complexity
