### ISSUE TITLE
Long press "s" not showing accented characters when language set to English

### ISSUE THREAD

**Issue by varistenmurha** [futo-org/android-keyboard#848] opened 2024-11-21 21:02 UTC
### What happened?

When long pressing on the s key while using the English language the only other letter available is ß. When language is set to Finnish it also shows š and ś. My keyboard layout is set to nordic on both languages, and other keys show all the same options.

Since there is no dictionary for Finnish I would prefer to set the language to English so I can at least use suggestions half the time, but I need š fairly often and it's annoying to have to switch language every time. 
![Screenshot_20241121_224251_FUTO Keyboard](https://github.com/user-attachments/assets/1b24af0b-34e6-4be7-b528-4466a0885576)
![Screenshot_20241121_224306_FUTO Keyboard](https://github.com/user-attachments/assets/328fa801-8875-4d16-b564-679f037de929)

### Keyboard Version

0.1.24-playstore

**Comment by dean-futo** [comment] 2024-11-21 21:59
Closing as duplicate of #683

**Closed by dean-futo** 2024-11-21 21:59 UTC
