### ISSUE TITLE
[REQUEST] Add option to swap microphone icon with others from next page.

### ISSUE THREAD

**Issue by vegedb** [futo-org/android-keyboard#201] opened 2024-07-05 16:17 UTC
## Problem
I don't usually use microphone BUT use clipboard a bunch on **Openboard**.
Seeing how the next page icons are "Draggable" to arrange, hope you could make it also swap with the microphone icon on main keyboard page just like **Openboard**.

### Change microphone to clipboard (Or others on next page)
![Clipboard Image (1)](https://github.com/futo-org/android-keyboard/assets/72070424/ee7b9d2d-4bf6-49c3-8028-cc8f1fed5e18)

### Openboard [Clipboard icon]
![image](https://github.com/futo-org/android-keyboard/assets/72070424/22a31cc2-e12b-43ca-b191-ff70bbb534e3)

**Comment by NagBoard** [comment] 2024-07-06 18:37
Duplicate of #33

**Comment by abb128** [comment] 2024-07-20 20:49
This will be included in the next release

**Closed by abb128** 2024-07-20 20:49 UTC
