### ISSUE TITLE
Grammar Correction When Language Changes is Broken 

### ISSUE THREAD

**Issue by AT181903** [futo-org/android-keyboard#768] opened 2024-11-05 07:46 UTC
### What happened?

I have 2 languages in FUTO keyboard (and also 2 languages in Android). When I use English (the primary language in Android) everything is ok. When I switch to my second language on the keyboard the grammar correction in the text field is in the primary language. 
This only happens with FUTO keyboard. 

### Keyboard Version

0.1.24

### Text field info

it happens in every text field

**Comment by dean-futo** [comment] 2024-11-07 20:27
Duplicate of #553 - merging this issue into that one.

**Closed by dean-futo** 2024-11-07 20:27 UTC
Labels: Bug Report, Medium Priority, High Complexity, Duplicate, Language Support
