### ISSUE TITLE
Swipe Actions

### ISSUE THREAD

**Issue by AtomToast** [futo-org/android-keyboard#93] opened 2024-06-30 09:49 UTC
Something that I really enjoy about Florisboard and AnySoftKeyboard is the ability to match actions to different swipes across the keyboard. This would conflict with having swipe typing enabled about would allow for things like:

- swipe down to close the keyboard
- swipe up to capitalize
- swipe left to delete the last word
- swipe right to accept the current word suggestion

but the possibilities are endless

**Comment by abb128** [comment] 2024-06-30 11:34
Duplicate of #65

**Closed by abb128** 2024-06-30 11:34 UTC
