### ISSUE TITLE
UK English £ symbol

### ISSUE THREAD

**Issue by EroticPlum** [futo-org/android-keyboard#973] opened 2024-12-21 23:17 UTC
### Language

English (UK)

### Description

1234567890@#$_%&-+()*"':;!?
$ should be £ default as it is UK keyboard

### Complexity

nope, just swap the symbols

**Comment by Solar-Simon** [comment] 2024-12-22 14:57
Nice, i just wanted to open the same issue, but for € Euro.

So maybe it would be nice to have the Option to choose your currency? And have one default for each Language?

**Comment by dean-futo** [comment] 2024-12-28 00:11
Closing as duplicate of #766

**Closed by dean-futo** 2024-12-28 00:11 UTC
