### ISSUE TITLE
Cursor slider should be in opposite direction for right-to-left languages

### ISSUE THREAD

**Issue by Coder-DG** [futo-org/android-keyboard#620] opened 2024-10-11 01:30 UTC
### What happened?

When using the cursor slider with the soacebar long press, cursor sliding direction is not reversed as it should be for languages that are written right to left. See how OpenBoard does it to understand (e.g. Arabic, Hebrew)

### Keyboard Version

0.1.23.2

**Comment by abb128** [comment] 2024-10-11 07:13
Duplicate of #450

**Closed by abb128** 2024-10-11 07:13 UTC
Labels: bug, new
