### ISSUE TITLE
[feature request] custom Portuguese layout

### ISSUE THREAD

**Issue by luigge** [futo-org/android-keyboard#189] opened 2024-07-05 02:58 UTC
so what I want to suggest is a custom layout for Portuguese similar to Spanish where in this case, to the right of "L" you have "Ç"

so basically the middle row would be 

asdfghjklç 

similar to the ABNT layout on external keyboards.

**Comment by abb128** [comment] 2024-07-05 10:50
Duplicate of #10

**Closed by abb128** 2024-07-05 10:50 UTC
