### ISSUE TITLE
Arabic diacritics went missing in V0.1.23

### ISSUE THREAD

**Issue by AnasImr** [futo-org/android-keyboard#343] opened 2024-07-23 13:34 UTC
So after updating the app from playstore to version 0.1.23, all the arabic diactricts that were supposed to be in the box specified in the screenshot below disappeared.
![Screenshot_20240723_130120_ColorNote](https://github.com/user-attachments/assets/67d59cdc-5066-4811-8a3c-8489eaf87626)
the red boxes in the screenshot are not all the diactricts that were there in previous versions, but they are just an example of what the diactricts look like
the full list of the diactrics is in this screenshot, taken in version 0.1.22:
![Screenshot_20240723_142926_FUTO Keyboard](https://github.com/user-attachments/assets/713e7001-025a-486d-9326-294922356ec2)
We just need them back in the app, thank you :)

**Comment by abb128** [comment] 2024-07-23 14:04
Hmm looks like this was an unintended consequence of #194, I thought I double-checked there'd be no regressions for Arabic/Farsi but this must've slipped through

**Comment by lippfi** [comment] 2024-07-23 14:51
Is 0.1.23 already out? When will it be available on F-Droid?

**Comment by abb128** [comment] 2024-07-23 15:46
@lippfi it's still being rolled out

@AnasImr This will be fixed in the next version. It might be some time but you can also use the nightly if this is necessary for typing: https://keyboard.futo.org/nightly.apk

**Comment by abb128** [comment] 2024-07-24 21:10
Will be fixed in 0.1.23.2

**Closed by abb128** 2024-07-24 21:10 UTC

**Comment by koutheir** [comment] 2025-12-01 01:59
The same problem happened again. Please fix this as it makes the keyboard useless for Arabic otherwise.
