### ISSUE TITLE
Auto-Correct Removes Space Before Punctuation That's Used With Traditional Emojis

### ISSUE THREAD

**Issue by dean-futo** [futo-org/android-keyboard#891] opened 2024-11-27 01:33 UTC
### What happened?

A user reports that auto-correct currently removes the space before punctuation like semicolons when you type traditional smileys [e.g., ;)].

resulting in text like this;)

instead of this ;)

There should be a way to prevent this from happening while still have autocorrect enabled, since traditional smileys are still often used.

### Keyboard Version

0.1.24

**Comment by abb128** [comment] 2024-11-27 15:32
Duplicate of #815

**Closed by abb128** 2024-11-27 15:32 UTC
Labels: High Priority, Low Complexity, Very High Priority, Triaged, Email
