### ISSUE TITLE
[Feature Request] Multiple languages at same time

### ISSUE THREAD

**Issue by PhilJbt** [futo-org/android-keyboard#74] opened 2024-06-29 22:02 UTC
I continually alternate between French and English writing. GBoard allows me to predict both languages, and this feature helps me a lot. Especially as many of my French sentences contain English words because of their technical aspect.

**Comment by CreaGab** [comment] 2024-06-29 22:49
I also hope that this will be implemented because I write in German, French and English almost on a daily basis.

**Comment by abb128** [comment] 2024-06-30 11:48
Seems to be duplicate of #38

**Closed by abb128** 2024-06-30 11:48 UTC
