### ISSUE TITLE
Add Support for Multilingual Auto-Correction

### ISSUE THREAD

**Issue by kittenvr** [futo-org/android-keyboard#461] opened 2024-08-14 07:39 UTC
### Use Cases

If I don't want to switch languages all the time

### Proposal

When jm typing it autocorrects for all my languages at once seemlessly like gbiard

**Comment by DamianS-eng** [comment] 2024-08-14 19:44
I'm against this, because of cognates and different fundamentals of sentence construction between languages.

Either make the language switching easier, or implement an automated learning method to understand which language is used (much harder imo).

**Comment by kittenvr** [comment] 2024-08-14 22:00
it works fine on gboard

**Comment by r-vdp** [comment] 2024-08-15 08:26
It works fine on gboard. I type in 3 different languages, and having to switch between them constantly is really annoying.

Also, code-switching is a thing, where multi-lingual people tend to use multiple languages even inside a single sentence, see https://en.wikipedia.org/wiki/Code-switching

**Comment by eug-vs** [comment] 2024-08-18 22:50
+1, I understand doing it might be really tricky but the use case is absolutely there. For example on GBoard I'm used to multiple languages with querty e.g English + Polish and it's smart enough to give reliable autocomplete.  What I would really love to see (not aware of any keyboard that does it) is to have multiple Slavic languages on the same layout, maybe sacrificing some characters for a long press. E.g Russian vs Belarusian keyboard layouts are practically the same except for 2 letters, I'd much rather long press once in a while instead of constantly switching beforehand. Might be related to this request, but that's a different issue I guess

**Comment by mayhair** [comment] 2024-08-19 06:20
[Heliboard](https://github.com/Helium314/HeliBoard) (an open source keyboard) has already implemented multilingual typing, if you want to check it out

**Comment by Philippe-Choquette** [comment] 2024-08-21 03:33
This is a duplicate of issue #38

**Comment by Chinoman10** [comment] 2024-08-31 12:48
This is the biggest painpoint I currently have after switching from Swiftkey which nailed this implementation perfectly IMHO.

I have English-Portuguese (basically a dual-dictionary) and English-French set, and it's super quick & easy to switch between them, I don't even think about it.

**Comment by lheinke** [comment] 2024-09-12 20:11
> I'm against this, because of cognates and different fundamentals of sentence construction between languages.
> 
> Either make the language switching easier, or implement an automated learning method to understand which language is used (much harder imo).

This is a sound argument against having multiple language autocorrect by default, but not against having it as an optional feature. I agree with the other users above that the current one language autocorrect is incredibly inconvenient for people that constantly switch between languages.

My suggestion would be to add toggles in the language selection menu such that users can freely toggle on and off single or multiple languages. There could also be a master toggle that restricts the selection by default to the single language mode.

**Comment by Chinoman10** [comment] 2024-10-02 09:49
As mentioned on a separate issue, I will unfortunately have to switch back to Swiftkey after these past horrible months of frustration.
I tried and insisted in using it, hoping it would get better over time... specially after buying the license to help support the project. But alas, I'll have to give up for now until this is implemented.

**Comment by hugohabicht01** [comment] 2024-10-30 16:00
This feature would make this keyboard app significantly more usable for me. I regularly write in both English and German,  but switching between keyboards is not a solution, as I regularly need to use English words in German, just because tech words don't really have a good translation. Additionally it's really annoying that the German language input method forces you to use qwertz instead of qwerty...

**Comment by dean-futo** [comment] 2024-11-03 00:38
Very similar to #478 - merging this issue into that one. Please comment on that thread if you have further input.

**Closed by dean-futo** 2024-11-03 00:38 UTC
Labels: Feature Request, High Priority, High Complexity
