### ISSUE TITLE
Manually Instruct Swipe Type for Desired Word

### ISSUE THREAD

**Issue by rexendevar** [futo-org/android-keyboard#183] opened 2024-07-04 22:14 UTC
I am a massive swipe type user, but it is simply not usable in the futo keyboard. Certain words are completely impossible to successfully swipe type; "swipe" itself does not even appear in the three suggestions more than maybe 5% of the time. If I am to ever train this keyboard I will need a more reliable way to instruct it of my intentions. I'd like to have the option of a little X or something in the suggestions after swipe typing a word that i can press and manually enter what word you intended to type so I'm not relying purely on luck to train it. For a sense of how bad it is, the main part of this text took me about three full minutes to type with swipe type.

**Comment by ptsgit270** [comment] 2024-07-09 23:56
I agree. I want to love this keyboard so much but I use swipe 95℅ of the time and as it stands I'm not seeing a way to help "train" my keyboard. I'm really trying to learn the feel of this keyboard but I will sit and try to swipe a word up to 10x times, vary my movements slightly, and not even see the word in the autocorrect bar, and just give up and type the word manually. 

I just had the keyboard try to place the letters "SBD" four times when I was trying to swipe "and." I've never once written "SBD."

**Comment by akirby83** [comment] 2024-08-12 19:41
I also find the swipe nigh unusable.  I'm not sure if it's because I swipe with my thumb and it's designed for people to swipe with their index finger or something.  It's one of the worst I've ever used and I hope the dev really takes a look at it.

**Comment by dean-futo** [comment] 2024-11-03 04:29
Duplicate of #363 - merging this request into that one.

**Closed by dean-futo** 2024-11-03 04:29 UTC
Labels: Feature Request, High Priority, Medium Complexity
