### ISSUE TITLE
Custom accent positions / Emoji search bar

### ISSUE THREAD

**Issue by Jprnp** [futo-org/android-keyboard#291] opened 2024-07-16 14:02 UTC
Hello! I've been using the keyboard with the portuguese language, and in portuguese, we tend to use a LOT of acute accents (é, á, ú, etc). Because of this, it feels right to make the acute accents the default accent when you hold down a letter. Right now it defaults to the symbols assigned to that position. 

So I'd really like if you could make it possible.to customize this behaviour.

Ankther thing that i miss from other keyboards is the possibility to search for emojis by text. Even if it only works in english would be helpful.

**Comment by abb128** [comment] 2024-07-16 15:05
Duplicate of #19 and #18

**Closed by abb128** 2024-07-16 15:05 UTC
