### ISSUE TITLE
emoji button hidden from keyboard after update

### ISSUE THREAD

**Issue by 8lec-R** [futo-org/android-keyboard#360] opened 2024-07-25 15:25 UTC
So the latest update which revamped the clipboard and additional settings menu has somehow managed to nuke the emoji button off my keyboard. Ik there's a page dedicated to be able to set an action button (which I have managed to fix by removing and readding it) but at start it should not show the emoji key being the action button when it is actually not (i.e in the settings it says emoji key is the action button, but on the keyboard there's nothing beside the comma key)
The solution is simple, if the users are aware, which I wasn't and found out by digging around.

**Comment by abb128** [comment] 2024-07-25 15:40
Duplicate of #335 and already fixed after 0.1.23.1

**Closed by abb128** 2024-07-25 15:40 UTC
