### ISSUE TITLE
[Featue Request] replace emoji key (with language switcher)

### ISSUE THREAD

**Issue by D3SOX** [futo-org/android-keyboard#43] opened 2024-06-26 22:49 UTC
I'd like to replace the emoji key with a one tap language switcher that rotates through all languages. I have a similar use case like #38. But I think this is much easier to solve so  this would be particularly useful to me until the multi language is implemented.

**Comment by abb128** [comment] 2024-06-27 06:16
Duplicate of #8 and already prepared for next update

**Closed by abb128** 2024-06-27 06:16 UTC

**Comment by D3SOX** [comment] 2024-06-27 16:04
Oops sorry didn't search for closed issues
