### ISSUE TITLE
feature suggestions

### ISSUE THREAD

**Issue by Kira-the-Meek** [futo-org/android-keyboard#375] opened 2024-07-27 05:03 UTC
version name: 0.1.23.2-playstore
version code: 10903

additional layout options for the numbers and characters board, such as this one
![Screenshot_20240726-231757](https://github.com/user-attachments/assets/2c44efdb-7918-4485-9124-24d8fa1b0b1c)

the ability for an automatic space after selecting a word suggestion 

the ability for commas to automatically place themselves at the end of the previous word even if there's already a space after it, and then put an automatic space after the comma 

an option for automatic additions to your personal dictionary based on word usage 

an "ingocnito mode" action as a quick toggle for when you don't want things automatically recorded into your dictionary

japanese language option with 12 key layout, such as this one 
![Screenshot_20240726-234726](https://github.com/user-attachments/assets/12f9316f-b566-43e2-82f8-36379a1a4656)

I think what you guys are doing is great, and this way good for just being in alpha. maybe some of these are already planned or they're already there and I just haven't found them in the hour or so I've had it, but I can't wait to see where things go from here

**Comment by abb128** [comment] 2024-10-10 20:25
Closing as duplicate of #64, #42, #605, #297, #514 and others

**Closed by abb128** 2024-10-10 20:25 UTC
