### ISSUE TITLE
Quotes Are Broken

### ISSUE THREAD

**Issue by issuant** [futo-org/android-keyboard#621] opened 2024-10-11 01:48 UTC
### What happened?

Suggestions seem to sometimes ignore what is typed if the word is preceded by a `"`. 
Typing out `"quote"` and then a `.` after it sometimes leads to `". "` instead of `"quote".`.

Related to #601, sometimes the first letter within the quote is auto capitalized and sometimes it isn't.
Related to #589, if you type out `"test"`, a space is not inserted until you type out the next character. This is misleading.

Related to #604, if you manually place the cursor to insert a `.` between two sets of quotes, like `"quote" |"quote"`, you get `"quote" . "quote"`, instead of `"quote". "quote"`. Typing `"a statement".` and then trying to begin the next with a quote too leads to `"a statement"."another"` instead of `"a statement". "another"`. Same thing happens even if there are words and other punctuation in between. Typing out two quote terms adjacent to each other leads to `"quote"" quote"` instead of `"quote" "quote"`. Manually placing the cursor to type a `.` just before the end of a quote leads to `"quote. "` instead of `"quote."`.

There are likely many more failure cases but at least for some cases, the issue seems to stem from FUTOBoard not recognizing the end of a quote. Some of these apply to single quotes too but that also seems to not even be recognized as a punctuation. Trying to type a `?` leads to `'is this a quote? '`, instead of `'is this a quote?'`.

### Keyboard Version

nightly

**Comment by abb128** [comment] 2024-10-11 16:09
> Suggestions seem to sometimes ignore what is typed if the word is preceded by a ".
> Typing out "quote" and then a . after it sometimes leads to ". " instead of "quote"..

Not sure what you mean here exactly, if you could provide a video or series of steps to understand that would be helpful if it's still happening

Most of the rest should be fixed in latest nightly (0.1.23.2-157-g3e29edca4). Apostrophes will not be treated as quotes for now because they're often used in English words in contractions or possessive cases, and implementing it would require careful consideration for something relatively minor and rare (though if it's important for your language please mention it)

**Comment by abb128** [comment] 2024-10-12 09:51
I can't reproduce the issue described. If you could provide more information or point out if I'm doing it wrong that would be helpful

[Screencast from 2024-10-12 12-48-40.webm](https://github.com/user-attachments/assets/66bc57c1-d9b0-4282-8960-cf9d9255e8a8)

**Comment by abb128** [comment] 2024-10-14 10:59
This was a bug with specifically the arrow keys causing the keyboard state to mess up, it will be fixed in the next nightly

**Closed by abb128** 2024-10-14 10:59 UTC
Labels: 🪲 Bug Report, High Complexity, Very High Priority
