### ISSUE TITLE
Add Option to Disable Update Checks Without Developer Settings

### ISSUE THREAD

**Issue by 737simpilot** [futo-org/android-keyboard#699] opened 2024-10-25 01:36 UTC
### Use Cases

In the keyboard at the top it says to check for updates every once in a while. It mentions that I can turn this off if it's annoying me in the developer options. I don't know what option I need to turn off in the developer options. Anyone happen to know?

### Proposal

Add an option to disable automatic update checks in the keyboard options its self rather than relying on developer options.

**Comment by dean-futo** [comment] 2024-10-25 22:09
Duplicate of #400 - merging this issue into that one. See #400 for details.

**Closed by dean-futo** 2024-10-25 22:09 UTC
Labels: Feature Request, High Priority, Low Complexity
