### ISSUE TITLE
Add Support for Multiple Dictionaries

### ISSUE THREAD

**Issue by BabyOilJohnson** [futo-org/android-keyboard#426] opened 2024-08-05 18:46 UTC
### Use Cases

I uses Heliboard, in there I can add multiple dictionaries for single language. For example I use manglish and experimental English ver of Heliboard.  

### Proposal

Adding multiple dictionaries support will be nice.

**Comment by dean-futo** [comment] 2024-11-14 23:24
Duplicate of #683 - merging this request into that one.

**Closed by dean-futo** 2024-11-14 23:24 UTC
Labels: Feature Request, Low Priority, Medium Complexity
