### ISSUE TITLE
Arrow keys to keyboard

### ISSUE THREAD

**Issue by wyorkovich** [futo-org/android-keyboard#523] opened 2024-09-01 12:11 UTC
### Use Cases

Using space bar long press or accessing the arrow keys via enter key long press is inconvenient and wastes time unnecessarily.

### Proposal

I came from SwiftKey yesterday after learning that Microsoft had shoved Copilot into it without my consent. One of my favorite features of SwiftKey that kept me using it for almost a decade was having all four arrow keys under the keyboard. In FUTO, long-pressing the space bar and and dragging to navigate the cursor is fine if you have to jump long distances in text, but it becomes difficult to use when you only need to navigate a few characters, which I find to be a fairly frequent occurrence. I know the arrow keys exist on the enter button's long press menu, but that's just as inconvenient to access as long pressing the space bar. Can we get them added to the bottom of the main keyboard?

**Comment by wagyourtail** [comment] 2024-09-05 07:32
I'd like to see a more complete "pc querty" layout that includes them in a way similar to hacker's keyboard has them

**Comment by Ser-Bul** [comment] 2024-09-10 09:48
I'm agree with the submitter and really look forward to see the feature implemented, yet the request looks like a duplicate of #54

**Comment by abb128** [comment] 2024-10-05 08:49
Duplicate of #54

**Closed by abb128** 2024-10-05 08:49 UTC
Labels: enhancement, new
