### ISSUE TITLE
Auto Language Switch for Different Apps

### ISSUE THREAD

**Issue by AndrehRemour** [futo-org/android-keyboard#362] opened 2024-07-25 19:29 UTC
i currently type in english in discord and portuguese in whatssap, but switch between the two everytime is really annoying, that's my only issue with this keyboard, a autoswitch for every app would a awesome feature, i know samsung keyboard already does that, but i don't really want to go back to with.

**Comment by Querzion** [comment] 2024-07-26 02:21
How do you suppose that would work? I myself write in English and Swedish in basically every application. It wouldn't serve the global community to have layout auto-switching embedded, most people have to switch between their native language and English in most applications. Sure I don't like the slow switching of a layout, SwiftKey is much faster, just swipe to the left or right. 

It would be nice however if you could write a phrase and it would know which language you are using based on the layouts you have installed though, and switch based on that. Don't know if it's viable though. "/

**Comment by mawkler** [comment] 2024-07-26 12:00
What SwiftKey does is to allow you to enable multiple languages for one single keyboard. I write in both Swedish and English and constantly switch between them. SwiftKey picks up which language I'm currently writing in based on the words I type, and starts suggesting sentence continuations in that language. I think this would be a killer feature for the FUTO keyboard as well; dynamic multi-language support.

**Comment by AndrehRemour** [comment] 2024-07-26 12:29
If it auto detect the language and them switch, that would be awesome. My problem is constantly switching between the two, and the way it is on futo keyboard is also anoying, you have to hold space bar-press on the language and then press on ok, on samsung keybard you could do that with just a key too.

**Comment by I-Dude** [comment] 2024-07-26 23:48
Have you updated the app to latest version? [v0.1.23.2](https://github.com/futo-org/android-keyboard/releases/tag/0.1.23.2)
There is a major quality of life added to switching languages.

**Comment by AndrehRemour** [comment] 2024-07-29 12:58
Just updated, i'll be testing the new version to see how it goes.

**Comment by haldi4803** [comment] 2024-10-05 04:56
See topic #38

**Comment by dean-futo** [comment] 2024-11-03 03:23
Duplicate of #683 - merging this issue into that one.

**Closed by dean-futo** 2024-11-03 03:23 UTC
Labels: Feature Request, High Priority, High Complexity
