### ISSUE TITLE
Spacebar is too narrow by default

### ISSUE THREAD

**Issue by tutacat** [futo-org/android-keyboard#975] opened 2024-12-22 18:41 UTC
### What happened?

With default settings, the spacebar is too narrow making it easy to accidentally hit other keys.

Some possible solution ideas:

- shrink the (?123), comma, and emoji-keys.
- move the emoji key to another row or the top bar
- add options during first-run startup for disabling emoji key, and similar
- allow moving settings popup to another key (like the emoji or enter key, or disabled). 
- Option to disable comma and emoji keys.

### Keyboard Version

0.1.24-playstore

**Comment by dean-futo** [comment] 2024-12-28 00:05
Closing as duplicate of #953. And you can already disable the emoji key in All Actions -> Edit Actions.

**Closed by dean-futo** 2024-12-28 00:05 UTC
