### ISSUE TITLE
[Feature Request] Delete whole words when swiping backspace.

### ISSUE THREAD

**Issue by robsdedude** [futo-org/android-keyboard#59] opened 2024-06-29 17:37 UTC
When swiping the backspace key with Gboard, it selects full words, not just single letters. This makes it much more convenient to delete a lot of text.

This could also be configurable in the settings, depending on how people prefer it to behave.

**Comment by abb128** [comment] 2024-06-29 20:15
Duplicate of #20

**Closed by abb128** 2024-06-29 20:15 UTC

**Comment by robsdedude** [comment] 2024-07-01 09:55
Thanks and sorry for the noise. I looked through the issues but must have missed this one.
