### ISSUE TITLE
Increase Symbol Hint Size for Improved Visibility

### ISSUE THREAD

**Issue by deadcombo** [futo-org/android-keyboard#47] opened 2024-06-29 07:59 UTC
Hello, I find the symbol hints rather small and often struggle to tell them apart in less than ideal lighting. Bit bigger would be nice.

Cheers.

**Comment by josb** [comment] 2024-06-30 04:45
Here's what they look like on SwiftKey using its "Pitch" theme.

**Comment by josb** [comment] 2024-06-30 04:50
Here's what symbols look like in SwiftKey, using its stock "Pitch" theme:
![20240629_205028](https://github.com/futo-org/android-keyboard/assets/50617/4bcb395e-7527-4b01-94fc-029d95b6fac9)

**Comment by kjkrum** [comment] 2024-07-01 02:09
This seems related to #90. The main font could be smaller and the hints bigger.

**Comment by dean-futo** [comment] 2024-11-15 07:18
Duplicate of #769 - merging this request into that one.

**Closed by dean-futo** 2024-11-15 07:18 UTC
Labels: Feature Request, Low Priority, Low Complexity

**Comment by chileverde** [comment] 2024-11-15 22:10
@dean-futo, Thanks for merging my issue with the previous one (which I hadn't seen).

Glad to know I'm not the only one who needs this!
