### ISSUE TITLE
[Feature request] Swipe Space to Change Language

### ISSUE THREAD

**Issue by PfalconR3d** [futo-org/android-keyboard#52] opened 2024-06-29 16:36 UTC
If we have multiple languages enabled , i would like to be able to swipe left or right the spacebar to change between the languages .
Long hold should still give the change language GUI .

**Comment by Tak0yaki** [comment] 2024-06-29 20:32
I agree with this.
This would be very helpful.

**Comment by ukrolelo** [comment] 2024-06-29 21:26
+1 :X

**Comment by Dryvnt** [comment] 2024-07-01 08:08
I quite appreciate swiping left/right on the spacebar to scroll the cursor, and would be sad to see it replaced with a language change.

My personal suggestion would be to have the language change GUI work with the same held spacebar input. To be more specific, I would personally like the following flow:
1. User taps and holds the spacebar to bring up the language change GUI.
2. While still holding the tap, User swipes upwards/downwards (alt. left/right). This scrolls an option highlight up/down in the language change GUI.
3. User releases their tap. The option highlighted in the language change GUI is selected, as if it were tapped.

If the user releases the held tap without swiping after step 1 (probably including some deadzone), current language change GUI behavior applies (tap to choose).

**Comment by lippfi** [comment] 2024-07-01 15:44
I would let user to choose if they want to scroll the cursor or change language on spacebar swipe
I do not like the "hold spacebar to bring a menu and scroll there" behavior because I do not use my cursor with spacebar and such behavior would bring unnecessary delay. It's not very different from what we have now

**Comment by Tak0yaki** [comment] 2024-07-01 18:10
Or you could do both where if you quickly swipe the spacebar it switches the language, but if you hold the spacebar then you scroll the cursor.

**Comment by daTokenizer** [comment] 2024-07-02 09:02
Maybe an up/down swipe can resolve this conflict

**Comment by PfalconR3d** [comment] 2024-07-02 15:37
The "up and down Swipe" as well as the "quick swipe vs long swipe" both sound great solutions , but i would much prefer if there were multiple choices . Anyone coming from swiftkey want that swipe right left for language . The cursor move is a gamechanger but its a feature that is rarely used while change language is heavily used anywhere in the world that doesn't use English as a primary language .

**Comment by DavidBevi** [comment] 2024-07-04 15:46
| | |
|-|-|
| I want to add on this topic. The picture is taken from the [Google Play Store page](https://play.google.com/store/apps/details?id=org.futo.inputmethod.latin.playstore&hl=en_GB&gl=US). </br></br> Said picture gives me a strong suggestion that the voice-dictation is triggered by holding the spacebar (which makes a lot of sense, and I'd want it). Since I explored all options I now think it doesn't work as the image suggested me. </br></br> But also, since reading the proposal in this thread, I like the idea of a language menu that is triggered by (hold+)swipe-up over the spacebar. </br></br> @devs, would it be possible to add "dictate in ENG", "dictate in ITA", ...? | ![image](https://github.com/futo-org/android-keyboard/assets/61429850/48a2658e-dd07-4cc0-8655-36b52eaf2cfd) |

**Comment by DavidBevi** [comment] 2024-07-04 17:04
>  The cursor move is a gamechanger but its a feature that is rarely used while change language is heavily used anywhere in the world that doesn't use English as a primary language.

Italian here. I see your point, but being used to Heliboard's multilingual input I disagree, because I never have to change language.

Also bonus tip I found out by chance, FUTO let's you _select_ text if you press shift and then swipe-to-move-the-cursor

**Comment by Somnius** [comment] 2024-07-05 02:42
I'm also a multi keyboard layout user, before i found this issue i've [posted on discord about it]( https://discord.com/channels/1224276522848751646/1224276522848751649/1258603269006299156), hoping for a solution soon

---

The worst part I wanted to be noted is the keyboard layout switching method, in order for me as a user to press and hold the space and then while having one or two hands focused on the lower end of the device I need to reach out to the top to select the language by hand.

I would suggest implemented a different approach via Spacebar slide left/right or even a dedicated keyboard layout switch button.

Last I'd like to thank the developers of FUTO keyboard, I'll keep trying to replace SwiftKey with FUTO and I also jumped on the donation / payment to the cause a while ago

Keep it up !! 👌🤘💪

**Comment by JustCryen** [comment] 2024-07-11 13:06
I personally prefer the up and down keyboard swype for language change but I just want to highlight the feature I just found out about.  
By clicking the expand icon ( > ) you can view and **swype** all the options. There is a language switch icon at the end but you can hold any option to **rearrange** them to make it more accessible.
This will result in two quick taps to switch the language instead of the spacebar method.

**Comment by abb128** [comment] 2024-07-14 13:25
The option to configure swiping the spacebar to switch languages will be included in the next release

**Closed by abb128** 2024-07-14 13:25 UTC
