### ISSUE TITLE
[Feature Request] Japanese input support

### ISSUE THREAD

**Issue by nikolaizombie1** [futo-org/android-keyboard#926] opened 2024-12-08 00:52 UTC
### Use Cases

Would allow Japanese speakers and typists to use FUTO instead of Swiftkey or Google Japanese Input. 

### Proposal

To start, the hiragana 12 key layout can be created to provide basic support for the language.

For a more complete solution, a Japanese IME must be integrated into FUTO. MOZC is a free and open source one that is commonly used in Android keyboards and Linux more broadly. This would allow for conversion of of hiragana to katakana or more importantly kanji.

Google Japanese input also provides handwritting input as well, albeit it's not that great.

**Comment by dean-futo** [comment] 2024-12-10 23:20
Closing as duplicate of #710

**Closed by dean-futo** 2024-12-10 23:20 UTC
