### ISSUE TITLE
Autocorrect Mistakes with 'xcvbn' Key Row

### ISSUE THREAD

**Issue by m1st0** [futo-org/android-keyboard#372] opened 2024-07-26 19:26 UTC
Issue: One of the simplest ways I don't see autocorrection is when the spacebar is easily missed and words are misspelled with the "xcvbn" letters.

Expected: Intelligence on autocorrect to recognize word mispeling with above letters.

Such that:
Onebnofvthesimplestbways I dontnsee . . .

**Comment by GOinfo-Ltd** [comment] 2024-07-28 09:32
I have to admit I didn't even think of opening this as an issue, but I do have the same problem.

**Comment by wings2004** [comment] 2024-07-31 13:54
Honestly I was going to recommend a feature that let you add padding between the space row and the bottom number row. That would help a lot for now.

**Comment by Tema726** [comment] 2024-08-01 11:34
Yes, this one!

**Comment by kispin** [comment] 2024-08-06 04:00
Same, I came here to make the same suggestion! I keep hitting B instead of the space bar.

**Comment by dean-futo** [comment] 2024-10-20 05:55
Consolidated into #666

**Comment by Webbeh** [comment] 2024-10-20 06:33
Thank you!

**Comment by dean-futo** [comment] 2024-10-23 18:45
Duplicate of #271 - see that issue for details.

**Closed by dean-futo** 2024-10-23 18:45 UTC
Labels: Bug Report, Very High Priority, Medium Complexity
