### ISSUE TITLE
Tidal app search bar: swipe doesn't work. 

### ISSUE THREAD

**Issue by gmccullo** [futo-org/android-keyboard#231] opened 2024-07-08 13:34 UTC
Tapping works fine tho.

**Comment by Doc-4** [comment] 2024-07-09 02:13
This is a duplicate issue of the more broad issue https://github.com/futo-org/android-keyboard/issues/37

**Comment by abb128** [comment] 2024-07-19 00:19
Duplicate of #37

**Closed by abb128** 2024-07-19 00:19 UTC
