### ISSUE TITLE
Backspace in reddit app

### ISSUE THREAD

**Issue by steviefaux** [futo-org/android-keyboard#14] opened 2024-06-05 19:57 UTC
When typing in the Android reddit app. If you mistype and have to backspace to erase your mistake, futo keyboard also deletes the space before the word even when your nowhere near that space.

Using other keysboard in the same app doesn't do this so this. So does appear to be a bug in the futo keyboard.

**Comment by GryphonIs** [comment] 2024-06-08 06:47
I'm having this issue too. Not just on reddit though.

**Comment by abb128** [comment] 2024-06-15 13:36
I can't seem to reproduce this issue, even in the Reddit app. Maybe I'm missing something. Would it be possible for you to record a video or detail the exact steps that cause the issue to happen?

**Comment by steviefaux** [comment] 2024-06-16 19:05
I'll set it up again and see if I can record a video.

**Comment by steviefaux** [comment] 2024-06-16 23:11
Uploaded a unlisted vid to my YouTube channel, hopefully that's OK?

https://youtu.be/_Wp_fHlcaOI?si=fhzFI2WGiTnyQvgd

Phone is a Samsung S23 Ultra
OS is One UI 6.1 / Android 14

Currently because of this bug the keyboard is unusable.

**Comment by abb128** [comment] 2024-06-18 17:36
Could you try this pre-release and let me know if the issue is fixed and if there's any other input-related problems? https://keyboard.futo.org/keyboard-0.1.21-7-gfdffadf6f.apk

**Comment by abb128** [comment] 2024-06-19 09:30
The fix has been pushed to v0.1.22 and should no longer occur, please let me know if there's any further issues

**Closed by abb128** 2024-06-19 09:30 UTC

**Comment by steviefaux** [comment] 2024-06-26 18:26
Sorry, don't check my e-mails enough. That has fixed it, thanks.
