### ISSUE TITLE
Multi-Finger Swiping Support (Two Thumbs)

### ISSUE THREAD

**Issue by EZ-eta** [futo-org/android-keyboard#114] opened 2024-07-01 17:43 UTC
I noticed that the keyboard correctly recognizes multi-fingers swiping and it has the possibility to use different model, so I thought it could be GREAT if it could implement a two-thumbs swiping model. Something similar to what Nintype AKA Keyboard69 was (for reference: https://youtu.be/xVVeq2EQPnI). On Android that keyboard stopped to work because it is 32-bit, but it didn't have any problems and to me is the Apex of virtual keyboard.
Plus it was completely offline, as FUTO.
I really hope to see a similar model implemented in near future, it would be the killer feature for me.

**Comment by jm355** [comment] 2024-10-17 00:02
This is the only feature that would get me to stop using thumb-key, multi-finger swiping is a massive upgrade from standard swiping.

Also, it seems like it might be possible to implement by just not ending the word on finger release, but using the spacebar, punctuation, or accepting a suggestion to end words instead

**Comment by EZ-eta** [comment] 2024-10-22 06:38
> This is the only feature that would get me to stop using thumb-key, multi-finger swiping is a massive upgrade from standard swiping.
> 
> Also, it seems like it might be possible to implement by just not ending the word on finger release, but using the spacebar, punctuation, or accepting a suggestion to end words instead

I am no expert in coding and stuff, but I agree with your idea: allowing the user to stop words just at the press of spacebar/punctuation might be enough. Hope this will be seen by developers and will be implemented soon, might sound niche, but there are a lot of persons used to type with Keymonk and Keyboard69/Nintype that would kill to have such a feature in a working and updated keyboard.

**Comment by dean-futo** [comment] 2024-11-15 07:09
Duplicate of #668 - merging this request into that one.

**Closed by dean-futo** 2024-11-15 07:09 UTC
Labels: Feature Request, Low Priority, High Complexity
