### ISSUE TITLE
NumPad layout for Number keys

### ISSUE THREAD

**Issue by rcarey1999** [futo-org/android-keyboard#411] opened 2024-08-01 13:42 UTC
### Use Cases

Number pad is very helpful when typing in a long string of numbers in a field that the keyboard does not recognize as a numeric field

### Proposal

Ideally an implementation similar to Gboard as shown below. 

Toggle button circled below. This number pad option would become available once clicking numbers toggle. 
![Screenshot_20240801_093712_Mull](https://github.com/user-attachments/assets/e7e18fb5-79a2-4abe-a5f2-c5336b153289)
![Screenshot_20240801_093452_GitHub](https://github.com/user-attachments/assets/98ee8606-0733-4522-a9b3-202ec20b7331)

Here is an attached video for further reference.

https://github.com/user-attachments/assets/f9ff4997-1127-40e1-a147-16c45011740b

**Comment by DamianS-eng** [comment] 2024-08-04 16:24
#64

**Comment by abb128** [comment] 2024-09-22 12:22
Duplicate of #64

**Closed by abb128** 2024-09-22 12:22 UTC
Labels: enhancement, new
