### ISSUE TITLE
Real-Time Voice Transcription

### ISSUE THREAD

**Issue by dean-futo** [futo-org/android-keyboard#883] opened 2024-11-26 04:13 UTC
### Use Cases

A user requests that we make it so words are transcribed as they are spoken in real-time, instead of processing them in batches after a delay. This would allow users to more presently keep track of grammar and punctuation accuracy.

### References

Email ticket #6444

**Comment by abb128** [comment] 2024-11-26 13:40
Duplicate of #130

**Closed by abb128** 2024-11-26 13:40 UTC
Labels: Feature Request, High Priority, High Complexity, Triaged, Email
