### ISSUE TITLE
Lagged Typing When Caps Lock Enabled

### ISSUE THREAD

**Issue by dean-futo** [futo-org/android-keyboard#905] opened 2024-11-29 20:40 UTC
### What happened?

A user reports that when caps lock is enabled and you start typing fast, the keyboard starts lagging.

### Keyboard Version

0.1.24

**Comment by MrLion28** [comment] 2024-12-03 12:57
This has been happening to me as well ever since the last "big" update. I remember users having lag some months ago but on my phone it was smooth (galaxy A22). Now whenever I type with caps it lags

**Comment by abb128** [comment] 2024-12-03 14:49
Duplicate of #873

**Closed by abb128** 2024-12-03 14:49 UTC
Labels: Bug Report, Very High Priority, Medium Complexity, Triaged, Discord
