### ISSUE TITLE
GIF selector and Emoji Search

### ISSUE THREAD

**Issue by FZephyr8** [futo-org/android-keyboard#261] opened 2024-07-13 02:30 UTC
Two features I missed when I switched from GBoard onto the Futo Keyboard were: a GIF search function where you can search for gifs from either tenor or gifhy (or both) as well as being able to search for your desired emoji, instead of having to scroll through the list of hundreds of emojis and hoping you find it.

**Comment by abb128** [comment] 2024-07-13 04:29
Duplicate of #83

**Closed by abb128** 2024-07-13 04:29 UTC
