### ISSUE TITLE
Fix Red Underlining in Hebrew Text Despite Dictionary Suggestions

### ISSUE THREAD

**Issue by Yuvalg1** [futo-org/android-keyboard#145] opened 2024-07-03 12:29 UTC
The words show up in suggested but It doesn't autocorrect the word as well. I tried both available dictionaries from the AOSP third party dictionaries, and it happens in both.

**Comment by NagBoard** [comment] 2024-07-03 13:06
Duplicate of #92

**Comment by dean-futo** [comment] 2024-11-04 03:27
Merging this issue into #92

**Closed by dean-futo** 2024-11-04 03:27 UTC
Labels: Bug Report, Medium Priority, Medium Complexity
