### ISSUE TITLE
Keyboard automatically moves cursor to the end of the word when tapping the middle of a word

### ISSUE THREAD

**Issue by Zishod** [futo-org/android-keyboard#267] opened 2024-07-14 14:38 UTC
When tapping in the middle of a word to move the cursor, for example to correct an error in the middle of a word, the cursor automatically moves to the end of the word instead of staying in the middle where I tapped. This behaviour seems to only happen when the last action taken in the keyboard is typing or if selecting the middle of the word would being up the keyboard.

https://github.com/user-attachments/assets/fa021b3b-6ba3-416d-bb39-5b6e135dfecf

**Comment by Zishod** [comment] 2024-07-19 02:05
This also seems to happen when sliding on the spacebar to move the cursor.

https://github.com/user-attachments/assets/ac2ba8cb-bf39-4af4-9df4-b0a8d4f4cb90

**Comment by FlorSilvestre12** [comment] 2024-07-30 15:28
I've been having a similar issue except sometimes my cursor will also move to a completely different word. And once when I was trying to correct parts of a multi paragraph post I'd written, the cursor would relocate to the end of the last paragraph after every individual backspace or new character added. It's really bizarre and doesn't seem to have a consistent trigger.

**Comment by ocouch** [comment] 2024-08-03 02:16
It would be great to have an option to disable this. A small thing, but very frustrating user experience.

**Comment by FlorSilvestre12** [comment] 2024-08-05 02:13
I just experienced the cursor getting persistently relocated to the end of the last paragraph again. I have only seen this happen while typing in the Reddit mobile app. The other relocation issue happens anywhere and everywhere.

**Comment by abb128** [comment] 2024-09-27 22:10
Duplicate of #98

**Closed by abb128** 2024-09-27 22:10 UTC
