### ISSUE TITLE
swipe typing

### ISSUE THREAD

**Issue by Shatakiii** [futo-org/android-keyboard#940] opened 2024-12-11 21:30 UTC
### What happened?

the keyboard is really nice but i am facing a few issues
1. the swipe typing is really inaccurate
2.the spell checker is showing white theme specifically on telegram everywhere else its fine i am attaching 1 video and 1 photo see those for reference

https://github.com/user-attachments/assets/95770ce6-0718-404c-ad19-288567b037b9
![Screenshot_20241211-180155~2](https://github.com/user-attachments/assets/7912bf09-feaf-47a6-8f02-a8cbdc60b68a)

### Keyboard Version

Version Name : V0.0.3-9-g650ccdc59- dirty

**Comment by dean-futo** [comment] 2024-12-14 22:03
Closing as duplicate of #363

**Closed by dean-futo** 2024-12-14 22:03 UTC
