### ISSUE TITLE
Multilingual suggestion in top bar

### ISSUE THREAD

**Issue by benedekfeke** [futo-org/android-keyboard#425] opened 2024-08-05 18:07 UTC
### Use Cases

Feature request: The top bar would suggest a word (or words) relevant to the actual word, context or correction, independent from the current chosen language on the keyboard.

Example: 
I'm on let's say Spanish, but quickly want to search the web in English, but don't want to switch the language to English. 
In the current version, the keyboard won't show me English suggestions for the typed English words, only Spanish. 
With the requested feature, the keyboard would suggest me English words, because it recognizes that I'm typing words from the English dictionary.

### Proposal

The keyboard may include more than 1 main languages (or all installed languages), as it is for example in Gboard.
The Gboard setting is shown in the third picture.

See: If I install 3 languages on Gboard, the Spacebar will include -and title- them all, choosing suggestions relevant to the typed word.
In FUTO keyboard, the spacebar only contains 1 language title - the selected one - and won't give suggestions from the other 2 installed languages.

![Screenshot_20240805-200415](https://github.com/user-attachments/assets/691dce8d-878a-4353-a92b-b968c5e27996)
![Screenshot_20240805-200450](https://github.com/user-attachments/assets/4e491912-e5e6-4914-b1c3-fcc33d0f4ee6)
![Screenshot_20240805-215725](https://github.com/user-attachments/assets/0072f7d4-c8a9-4a45-a5be-d7435a296601)

**Comment by The-Quantum-Alpha** [comment] 2024-08-05 19:51
I Endorce this idea.

**Comment by gamberoillecito** [comment] 2024-08-06 18:30
I think this is extremely useful for bilingual people, I'm extremely used to it on gboard and it's a bit annoying right now with futo

**Comment by galaxios** [comment] 2024-08-08 23:57
I hope this can be done, I loved the keyboard but ended up switching back to Gboard after a while because of how annoying it gets to need to switch languages all the time

**Comment by abb128** [comment] 2024-08-09 17:26
Duplicate of #38

**Closed by abb128** 2024-08-09 17:26 UTC
Labels: enhancement, new
