### ISSUE TITLE
[Feature Request] Japanese Language Support

### ISSUE THREAD

**Issue by tommydrum** [futo-org/android-keyboard#176] opened 2024-07-04 14:59 UTC
First off, awesome work here, the English side does work just about flawlessly, that said I also speak and often speak to Japanese people, making the lack of Japanese a non-starter for me...

(While the qwerty version of Japanese would work fine, the 12 key system is the standard.. Ideally having them both would be nice)

**Comment by jonathan-s** [comment] 2024-07-06 05:52
Duplicate of #42

**Comment by tommydrum** [comment] 2024-07-09 00:54
Duplicate of 42, sorry, closing.

**Closed** 2024-07-25 03:11 UTC
