### ISSUE TITLE
Deletion Issues

### ISSUE THREAD

**Issue by AlexanderTheGr3at** [futo-org/android-keyboard#16] opened 2024-06-10 15:47 UTC
When deleting text that was misspelled sometimes the keyboard removes the space between the previous two words. For example, if I were writing "and I went to the perk" and needed to change the 'e' in 'perk' to an 'a' for 'park' it would so this as I'm deleting. "And I went to theprk" after I delete the 'e'.

**Comment by abb128** [comment] 2024-06-15 13:35
This seems to be a duplicate of #14. I can't seem to reproduce it at the moment though

**Closed by abb128** 2024-06-15 13:35 UTC
