### ISSUE TITLE
Crash When Using Russian Voice Recognition with Multilingual Model

### ISSUE THREAD

**Issue by deadsqrl** [futo-org/android-keyboard#680] opened 2024-10-21 13:14 UTC
### What happened?

When tried to use voice recognition on Realme C3 RMX2021 app crashes and voice recognition not working for Russian language. Here is crash report:
[Crash.txt](https://github.com/user-attachments/files/17461362/Crash.txt)

### Keyboard Version

0.1.23.2

### Text field info

Happens on every input

**Comment by dean-futo** [comment] 2024-11-04 02:12
Likely duplicate of #664, which has been fixed. See that issue for details and solution.

**Closed by dean-futo** 2024-11-04 02:12 UTC
Labels: Bug Report, Medium Priority, Medium Complexity

**Comment by dean-futo** [comment] 2024-11-04 02:13
Voice input crashes were common in various circumstances until a recent fix in the nightly build. See #664 for details.
