### ISSUE TITLE
[Feature request] Swipe space to change language

### ISSUE THREAD

**Issue by ukrolelo** [futo-org/android-keyboard#70] opened 2024-06-29 21:24 UTC
Pleeeaasee i have 4 languages that i need to change between <3. P.S.I was using samsung keyboard and when i  typed with mistakes i thought it is me. But with this keyboard my keypress is exactly what i want to press, how the F you created better typing experience than Samsung???? <3

**Comment by ukrolelo** [comment] 2024-06-29 21:27
Duplicate :-X sorry
https://github.com/futo-org/android-keyboard/issues/52

**Comment by abb128** [comment] 2024-06-30 11:46
Closing as duplicate of #52

**Closed by abb128** 2024-06-30 11:46 UTC
