### ISSUE TITLE
Customize Expiration Time for Unpinned Clipboard Entries

### ISSUE THREAD

**Issue by dean-futo** [futo-org/android-keyboard#881] opened 2024-11-26 03:59 UTC
### Use Cases

A user requests that add the ability to customize the expiration times for unpinned clipboard entries, allowing you to set how long recent entries are kept before they are automatically deleted.

### References

Email ticket #6494

**Comment by abb128** [comment] 2024-11-26 13:42
Duplicate of #119, #225 (they should probably be consolidated)

**Closed by abb128** 2024-11-26 13:42 UTC
Labels: Feature Request, Low Priority, Low Complexity, Triaged, Email

**Comment by dean-futo** [comment] 2024-11-27 00:16
@abb128 merged them into #225.
