### ISSUE TITLE
Random Lags and Freezes During Keyboard Input

### ISSUE THREAD

**Issue by creeper82** [futo-org/android-keyboard#868] opened 2024-11-24 11:33 UTC
### What happened?

At very random moments, the keyboard freezes for a second or two and then pushes all the input pressed during that period

Happens both when typing quickly and slowly. Happens with any keyboard language. I could not find any correlation or steps to reproduce. An example can be seen in the video. The text I type in the video doesn't have any significance for the issue. I have Snapdragon 8+ gen 1, and a lot of free RAM so hardware can't be the issue

https://github.com/user-attachments/assets/0cd7cf4f-5213-4514-8bf2-2a487800859d

**This did not happen before updating to v0.1.24**

### Keyboard Version

0.1.24

### Text field info

Various apps. Mostly WhatsApp, Discord, Messenger, but not limited to them.

**Comment by creeper82** [comment] 2024-11-24 11:34
Also it's interesting how it types it word-by-word and freezes after typing whole word , just like it wasn't a random freeze but some bug with keys?

**Comment by abb128** [comment] 2024-11-26 16:04
How often does this happen? I couldn't reproduce it. Can you check and see if it occurs in nightly? https://keyboard.futo.org/nightly.apk

**Comment by dean-futo** [comment] 2024-11-27 00:35
I was not able to reproduce this in nightly.

**Comment by abb128** [comment] 2024-12-03 15:24
If it's not fixed in the latest nightly let me know

**Closed by abb128** 2024-12-03 15:24 UTC
Labels: Bug Report, Very High Priority, Medium Complexity, Triaged
