### ISSUE TITLE
Auto-Capitalization Not Disabled After First Sentence

### ISSUE THREAD

**Issue by booflesnoof** [futo-org/android-keyboard#252] opened 2024-07-11 02:12 UTC
i prefer to type in all lowercase, but it always auto-capitalizes the first word of every sentence after the first, despite that option being disabled. this happens on my Samsung Galaxy Note 8 as well as Samsung Galaxy A14 5G, v0.1.22-playstore

**Comment by dean-futo** [comment] 2024-10-20 03:55
Consolidated into #663

**Comment by dean-futo** [comment] 2024-10-23 23:42
Duplicate of #547 - see that issue for details.

**Closed by dean-futo** 2024-10-23 23:42 UTC
Labels: Bug Report, Low Complexity, Very High Priority, Consolidated
