### ISSUE TITLE
Add GIF Search Functionality via External API/Website

### ISSUE THREAD

**Issue by kf7mxe** [futo-org/android-keyboard#83] opened 2024-06-30 01:42 UTC
Be able to search gifs from Giphy. If possible be able to change the website/api to search gifs for. 

Also if we end up implementing any of these features ourselves is there a way to make a pull request to share the feature with others?

**Comment by abb128** [comment] 2024-06-30 11:57
The keyboard doesn't have the internet permission, so implementing this within the keyboard wouldn't work without breaking the core promise of no connecting to the internet. It may be possible to develop a system for optional external add-on apps with internet permission to carry out tasks like this, but this may get complicated

**Comment by digitalkram** [comment] 2024-06-30 13:46
Wouldn't that be similar to the TTS plugin that has internet access?

**Comment by abb128** [comment] 2024-06-30 15:19
> Wouldn't that be similar to the TTS plugin that has internet access?

The integrated voice input doesn't have internet access, it runs on your phone.

**Comment by digitalkram** [comment] 2024-06-30 19:21
I know and read that. One of the reasons I considered taking it to a test drive. I saw in appinfo that it has requested no permissions and the data counter is 0. I was probably mislead by the fact that the futo keyboard app has a grayed-out "allow network access" toggle while futo voice input can be toggled there (off-topic, but why?) Back to topic: Generally I was more referring to the idea of a add-on/plugin system that could have existed because why else would something called 'built-in' be separate. But obviously I was mistaken here.

**Comment by MulverineX** [comment] 2024-07-07 21:28
As long as GIF search is disabled by default I don't really see the problem with this. Even if an addon system was implemented, that would still require internet access to be enabled so that the plugin itself once installed could make requests.

**Comment by MulverineX** [comment] 2024-07-07 21:30
Another nice system to have would be a favorites section where you can favorite specific gifs by long pressing on them, that can be a separate issue though. Also it would be neat if there was a page in settings that allowed you to manually add gif URLs and local files (including non-animated images) to your favorites.

**Comment by MulverineX** [comment] 2024-07-07 21:31
This is currently one of the most blocking reasons I choose Gboard for now, really looking forward to this being done eventually.

**Comment by dean-futo** [comment] 2024-11-03 03:41
Duplicate of #283 - merging this issue into that one.

**Closed by dean-futo** 2024-11-03 03:41 UTC
Labels: Feature Request, Low Priority, High Complexity, Duplicate

**Comment by digitalkram** [comment] 2024-11-03 09:32
@dean-futo is #283 really a duplicate? Maybe you mistyped the number?

**Comment by anseltaft** [comment] 2025-07-01 20:09
> [@dean-futo](https://github.com/dean-futo) is [#283](https://github.com/futo-org/android-keyboard/issues/283) really a duplicate? Maybe you mistyped the number?

Yeah, it should be #293
