### ISSUE TITLE
Keyboard Frequently Enables Caps Lock Unexpectedly

### ISSUE THREAD

**Issue by 1-NoLimits** [futo-org/android-keyboard#286] opened 2024-07-16 06:25 UTC
Maybe just me but when I return to any app (eg whatsapp) I noticed the caps lock is on.

Not sure why but ban we get an option to disable this?

**Comment by The-Quantum-Alpha** [comment] 2024-07-16 06:29
[It will be fixed for the next release](https://github.com/futo-org/android-keyboard/issues/246#issuecomment-2226769694)

**Comment by dean-futo** [comment] 2024-10-20 05:17
Consolidated into #663

**Comment by dean-futo** [comment] 2024-10-23 23:33
Duplicate of #154 - see that issue for details.

**Closed by dean-futo** 2024-10-23 23:33 UTC
Labels: Bug Report, Low Complexity, Very High Priority
