### ISSUE TITLE
[Feature Request] Add number pad option

### ISSUE THREAD

**Issue by sierrapappabravo** [futo-org/android-keyboard#364] opened 2024-07-26 00:11 UTC
Add an option to have a number pad on the numbers (?123) screen instead of the number bar on top. An example of this is the layout setting in SwiftKey that allows changing from the nunber row to left or right sided number pad.

**Comment by Localhorst86** [comment] 2024-07-26 16:16
A numpad layout already seems to exist, but is only activated in numeric input fields (like adding a phone number to a contact).

I would like to be able to change the default "secondary" keyboard layout (the one we get when pressing the ?123 button) to an "enhanced" numpad layout that includes most/all special characters from the ?123 layout, but arranges the numbers in a numpad orientation, leaving us access to special characters, like swiftkey has (see screnshots)
![Screenshot_20240726-181501](https://github.com/user-attachments/assets/d04133fe-d288-447a-9d75-eb70022414c2)
![Screenshot_20240726-181515](https://github.com/user-attachments/assets/b1583a85-6489-4950-a985-b01046b0a6d7)

**Comment by abb128** [comment] 2024-07-27 19:49
Duplicate of #64

**Closed by abb128** 2024-07-27 19:49 UTC
