### ISSUE TITLE
[Feature Request] Quick language change via Swipe spacebar left and right

### ISSUE THREAD

**Issue by the-mentor** [futo-org/android-keyboard#111] opened 2024-07-01 08:18 UTC
Pretty much what the title says.
Swift key implements this and it's vital for multi language support to be on par with other keyboards.

Edit: I attached a video to show the feature I'm requesting

**Comment by the-mentor** [comment] 2024-07-01 08:18
https://github.com/futo-org/android-keyboard/assets/11185446/0b684d58-f19e-4b3b-8cd5-c7a6a79b01c5

**Comment by lippfi** [comment] 2024-07-01 12:38
As far as I know, the language switch button is going to be added in the next release, either instead of or next to the emoji button. 

However, support for switching languages via swiping on the spacebar should also be supported. 

Why? 

Because some people use not just two, but three languages. There is a use case where you are typing in your native language, switch to English to type a word, and then want to switch back by swiping in the opposite direction. Using a button to switch languages is not as convenient in this case, because if you have N languages added, you would need to tap the switch language button N - 1 times.

Additionally, the spacebar should display which language is currently selected. This is important because there are languages with the same alphabet, and you can’t always tell which one is active just by looking at the keys.

**Comment by NagBoard** [comment] 2024-07-01 15:03
Duplicate of #52

**Comment by abb128** [comment] 2024-07-14 13:26
Duplicate of #52 and the option will be included in the next release

**Closed by abb128** 2024-07-14 13:26 UTC
