### ISSUE TITLE
[FEATURE REQUEST] Add some more `actions`

### ISSUE THREAD

**Issue by arbitrary-dev** [futo-org/android-keyboard#932] opened 2024-12-09 07:03 UTC
### Use Cases

Useful in terminal and other text editing cases. 

### Proposal

`q`: `ESC`
`e`: `END` (moves cursor to the end of a line)
`h`: `HOME` (... to the beginning ...)
`t`: `TAB`

**Comment by dean-futo** [comment] 2024-12-10 23:37
Closing as duplicate of #25

**Closed by dean-futo** 2024-12-10 23:37 UTC
Labels: Duplicate
