### ISSUE TITLE
Add Support for Email Addresses in Dictionary Predictions

### ISSUE THREAD

**Issue by Dan-Burgess** [futo-org/android-keyboard#515] opened 2024-08-29 00:13 UTC
### Use Cases

Email addresses are commonly used strings that are resistant to prediction. Futo allows these to be added to a dictionary but they do not show up in predictions.

### Proposal

Allow prediction of strings containing non-alphanumeric characters.

**Comment by weedy** [comment] 2024-09-07 15:03
#248

**Comment by dean-futo** [comment] 2024-11-10 23:54
@weedy this is indeed a duplicate of #248. Merging this request into that one.

**Closed by dean-futo** 2024-11-10 23:54 UTC
Labels: Feature Request, Low Priority, Low Complexity
