### ISSUE TITLE
Additional space added after choosing suggested word

### ISSUE THREAD

**Issue by GingerNinjaXL** [futo-org/android-keyboard#479] opened 2024-08-16 12:29 UTC
### What happened?

An extra space is added at the start of a word when trying to go back and change an autocorrect to a suggested word.

1. Type a word incorrectly - e.g. "examplr"
2. Press space that causes the word to autocorrect - "example "
3. Press backspace to undo the autocorrect - "examplr"
4. Now choosing a word on the suggestion bar adds a space before the word - " example", or " Example" depending on word in suggestion bar chosen.

This occurs no matter the proceedings character/word.

### Keyboard Version

0.1.23.2-playstore

**Comment by mmoole** [comment] 2024-08-18 20:11
This seems to happen also when not using the autocorrected one but any suggestion without pressing space:
1. swype a part of a word, e.g. `Maximal`: this results in `Maximal` being entered (without space)
2. continue typing or swyping `geschwindigkeit`: this results in a space being added in front of the word and autocorrect applied, resulting in `Maximal Geschwindigkeit`
3. It should result in `Maximalgeschwindigkeit`, but it seems there is no way to use suggestions or autocorrect together with longer words. 
4. Having tapped every character manually, the result would be correct, but it would take the maximum amount of time to do so.

I would add that it's not so practical to have spaces automatically inserted at all for some use cases / languages. For example, in German there are a lot of words 'combined' by just concatenating parts of words. But when typing/swyping words like `Maximalgeschwindigkeit` or longer words, one has to remove the space and de-capitalize the 'G' if swyping it via the two parts `Maximal` and `geschwindigkeit` despite having proactively taken capitalization into account. It makes much sense to swype parts of words because longer words are often not recognized by most keyboards.

If this is a feature, please make it optional - it could of course be enabled by default, but the user should be able to disable any space characters being auto-inserted when using suggestions or at all.

(Keyboard Version 0.1.23.2-playstore)

**Comment by KaKi87** [comment] 2024-09-11 08:49
Duplicate of #190

**Comment by abb128** [comment] 2024-10-10 18:35
This should be fixed in nightly and the fix will be included in the next release.

**Closed by abb128** 2024-10-10 18:35 UTC
Labels: bug, new
