### ISSUE TITLE
Unclear How to Disable This Behavior in Clipboard Manager

### ISSUE THREAD

**Issue by Noth1ngLol** [futo-org/android-keyboard#289] opened 2024-07-16 10:58 UTC
https://github.com/user-attachments/assets/a4899fbc-d494-40d7-b312-798bdde3d4da

**Comment by dean-futo** [comment] 2024-10-28 01:32
Duplicate of #583 - merging this ticket into that one.

**Closed by dean-futo** 2024-10-28 01:32 UTC
Labels: Bug Report, Very High Priority, Medium Complexity
