### ISSUE TITLE
[feature request] Automatic "private browsing," detection

### ISSUE THREAD

**Issue by zachHixson** [futo-org/android-keyboard#208] opened 2024-07-06 17:46 UTC
Something I noticed the default Google keyboard does is automatically detect when the user enters private-browsing/incognito-mode and switches the keyboard over to mode which stops recording what the user types. 

While not a super crucial feature, I feel like it would be a welcome one since the keyboard is trying to build an image of privacy

**Comment by The-Quantum-Alpha** [comment] 2024-07-06 18:15
I don't think this is necessary as the keyboard is completely offline.

**Comment by swishkin** [comment] 2024-07-06 19:01
I think the option to exclude text entered and clipboard entries created during private browsing from influencing the behavior of the keyboard afterwards and would be worthwhile, including any change to predictive text and the contents of the clipboard.

**Comment by abb128** [comment] 2024-07-06 19:05
Duplicate of #78

**Closed by abb128** 2024-07-06 19:05 UTC
