### ISSUE TITLE
[feature-request] T9 keyboard option in number/character keyboard

### ISSUE THREAD

**Issue by skj-skj** [futo-org/android-keyboard#371] opened 2024-07-26 15:50 UTC
when typing long numbers or 4-6 digits pin I find it useful to use T9 keyboard layout in the Gboard.

Screenshot example:
![Screenshot-T9-Keyboard-Layout](https://github.com/user-attachments/assets/cb7a3bbd-d74b-46f0-83ed-7b12ee424097)

Thanks.

**Comment by abb128** [comment] 2024-07-27 19:48
Duplicate of #64

**Closed by abb128** 2024-07-27 19:48 UTC
