### ISSUE TITLE
Cursor jumping to the end of selected words

### ISSUE THREAD

**Issue by fooolerie** [futo-org/android-keyboard#551] opened 2024-09-15 08:13 UTC
### What happened?

When 'Show correction suggestions' and 'Transformer LM' are both enabled there's some odd cursor behaviour when attempting to position the cursor within a word (i.e. for editing purposes), namely the cursor jumps to the end of the word a short moment after placing it.

Expected behaviour: Cursor stays where it has been placed.

Specifics: 
- This happens only when 'Show correction suggestions' and 'Transformer LM' are both enabled simultaneously. 
- Whether 'Auto-correction' is enabled or not has no influence.
- This only happens if you move the cursor after completing the current word, i.e. the last action was not a backspace. 
- Whether either word (final word before moving the cursor or word the cursor is moved to) is spelled correctly has no influence; any string of letters, no matter the length (e.g. 'example' or 'examplw' or 'e'), is recognised as a word.
- Either word consisting entirely of a string not recognised as a word (e.g. '%$&#' or '1234') will not cause the behaviour.
- Both tapping and dragging to move the cursor replicate this same behaviour.

Aside: 
Some other unusual behaviour I noticed while testing, whether you consider it a bug or not I don't know - words do not have to be seperated by whitespace to be recognised as as individual words, any non-letter character serves the same purpose (e.g. 'ex@mple' is recognised as two words, 'ex' and 'mple')

(edit: clarity and source correction)

### Keyboard Version

v0.1.23.2
Source: GitHub through Obtanium

**Comment by cathalferris** [comment] 2024-09-15 22:41
I have observed similar behaviour - but for me the reposition to the end is not predictable, Sometimes it will reposition with just enough of a delay to cause the move to be missed as I start to type, and at other times the cursor will not move. The inconsistency is moderately frustrating - especially if the cursor is placed between a space and the start of a word with the intention of typing a word to insert, and finding that the typed input has been appended instead of prepended.

Version 0.1.23-2-playstore, paid version
German, externally imported voice, built-in dictionary, no transformer, Qwerty keyboard
German (Switzerland), externally imported voice, built-in dictionary, no transformer, Qwerty keyboard
English (Ireland), externally imported voice, built-in dictionary, English v1 transformer, Qwerty keyboard
Almost exclusively using English-language entry.

Thank you!

**Comment by kuiper23** [comment] 2024-09-18 16:49
Great keyboard. I'm a proud paid user. But I'm experiencing this issue too, and its driving me crazy. (Okay, thats a bit dramatic, but I would really like to see it get fixed).

**Comment by alanthird** [comment] 2024-09-26 14:32
I'm reasonably sure that  #267, #369 and #562 are also about this issue. #98 looks like it probably is too, although it mentions another couple of things that may be unrelated.

**Comment by abb128** [comment] 2024-09-27 22:09
Duplicate of #98

**Closed by abb128** 2024-09-27 22:09 UTC
Labels: bug, new
