### ISSUE TITLE
English UK Should swap "$" for "£" on the primary punctuation layout

### ISSUE THREAD

**Issue by te-simps** [futo-org/android-keyboard#927] opened 2024-12-08 14:57 UTC
### Language

English (UK) 

### Description

With English (UK) selected as the keyboard language, the primary punctuation screen still features "$" whereas it should be the primary currency of the UK i.e. "£". I would request that these are swapped on the two punctuation screens. 

### Complexity

Low

**Comment by dean-futo** [comment] 2024-12-10 23:31
Closing as duplicate of #766

**Closed by dean-futo** 2024-12-10 23:31 UTC
Labels: Duplicate
