### ISSUE TITLE
[Bug] Predictive text disappeared, in Github text editor

### ISSUE THREAD

**Issue by maxleirbag** [futo-org/android-keyboard#120] opened 2024-07-01 23:11 UTC
Despite all of the relevant settings enabled for the predictive text functionality, the word suggestion vanished while using Github for Android (official app).

This undesired behavior doesn't happen in other applications.

**Comment by Exp-01** [comment] 2024-07-02 14:14
Thats probaby githubs fault. maybe they could make a setting for forcing it on

**Comment by NagBoard** [comment] 2024-07-03 13:22
Duplicate of #108

**Comment by abb128** [comment] 2024-07-25 04:35
This should be fixed in 0.1.23

**Closed by abb128** 2024-07-25 04:35 UTC
