### ISSUE TITLE
Bulgarian Phonetic layout

### ISSUE THREAD

**Issue by capsit95** [futo-org/android-keyboard#420] opened 2024-08-04 13:34 UTC
### Language

Bulgarian

### Description

![IMG_20240804_163058](https://github.com/user-attachments/assets/6dd3d4bf-ab13-4064-a20e-7d21c23e93da)

This is how the layout looks in Gboard. Thank you for considering this addition - it would really make this keyboard perfect for me.

**Comment by abb128** [comment] 2024-08-04 15:53
Duplicate of #63

**Closed by abb128** 2024-08-04 15:53 UTC
Labels: new, layout
